- java/src/main/java/org/wildfly/openssl/OpenSSLSocket.java
Fixing calling of incorrect method for the proper one.
> WFLY-7704: enableCipherSuite proper call delegation to sslEngine

- combined/pom.xml
- java/pom.xml
- pom.xml
Separated build on linux to separate profiles one for 32bit system and
one for 64bit system. The separation is based on system property
sun.arch.data.model
> Separated linux building by architecture.

- libwfssl/src/session.c
There seems to be an inconsistency between the JNI function declarations in Oracle and IBM JDKs for the last arg of SetByteArrayRegion (really, all functions like this).
Oracle v8 uses const jbyte *
void (JNICALL *SetByteArrayRegion)
(JNIEnv *env, jbyteArray array, jsize start, jsize len, const jbyte *buf);
whereas IBM v8 uses jbyte *
void (JNICALL * SetByteArrayRegion)(JNIEnv *env, jbyteArray array, jsize start, jsize len, jbyte *buf); 
This patch allows for compilation under both the Oracle and the IBM JDKs.
> Fix compilation on IBM JDK

- linux-i386/Makefile
- linux-x86_64/Makefile
- macosx-x86_64/Makefile
- solaris-sparcv9/Makefile
- solaris-x86_64/Makefile
This patch adds a few standard variables to the UNIX Makefiles, namely, CC, CFLAGS, and LDFLAGS.
In particular, CFLAGS and LDFLAGS are needed to allow the proper compiler and linker flags to be passed when compiling on RHEL. Otherwise, compilation may fail on these Linux distributions.
The Windows Makefiles have been left as-is.
> Allow setting of CC, CFLAGS, and LDFLAGS in UNIX Makefiles

- java/src/main/java/org/wildfly/openssl/Messages.java
- java/src/main/java/org/wildfly/openssl/OpenSSLContextSPI.java
- java/src/main/resources/org/wildfly/openssl/OpenSSLMessages.properties
Added handling of NPE documented in JBEAP-10396.
https://issues.jboss.org/browse/WFSSL-7
https://issues.jboss.org/browse/JBEAP-10396
> [WFSSL-7] Handling of NPE on obtaining PrivateKey from FIPS PKCS11 key manager

- java/src/main/java/org/wildfly/openssl/ByteBufferUtils.java
- java/src/main/java/org/wildfly/openssl/Messages.java
- java/src/main/java/org/wildfly/openssl/util/DirectByteBufferDeallocator.java
- java/src/main/resources/org/wildfly/openssl/OpenSSLMessages.properties
@stuartwdouglas, when trying to build the project with Java 9, I ran into runtime exceptions (reproducible in the existing tests) in the ByteBufferUtils which tries to get a cleaner to clean the direct bytebuffers. Exceptions of the form:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.wildfly.openssl.ByteBufferUtils (file:/opt/wildfly/wildfly-openssl/java/target/classes/) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.wildfly.openssl.ByteBufferUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 2, Failures: 0, Errors: 2, …
```
> Fix ByteBufferUtil to make it work in Java 9

- macosx-x86_64/Makefile
While building the project on MacOS (Sierra) with Java 8:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
the build fails with:
```
[INFO] --- exec-maven-plugin:1.5.0:exec (default) @ wildfly-openssl-macosx-x86_64 ---
mkdir -p target/classes/macosx-x86_64
cc  -Werror -Wall -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wpointer-arith -std=c89 -Wdeclaration-after-statement -Wformat -Wformat-security -Wunused -Wno-unknown-pragmas -c ../libwfssl/src/alpn.c -o target/alpn.o -I../libwfssl/include
In file included from ../libwfssl/src/alpn.c:2:
../libwfssl/include/wfssl.h:41:10: fatal error: 'jni.h' file not found
#include <jni.h>
^
1 error generated.
make: *** …
```
> Fix build on MacOS with Java 8

- java/src/main/java/org/wildfly/openssl/OpenSSLSocket.java
Hi @stuartwdouglas, the commit here fixes the issue reported here https://github.com/wildfly/wildfly-openssl/issues/31
The change propagates `-1` back from the `OpenSSLSocket#read()` upon EOF.
> Propogate back EOF from read() on OpenSSLSocket

- pom.xml
- This version has been accidentally updated during `wildfly-openssl`
version bump by 9a20fc6 commit from `1.0.4.Final`. As `1.0.5.Final`
has been already released, using this version instead.
As version of `wildfly-openssl` matches `checkstyle` version again. We need to watch out what versions are bumped during the next release.
> Fixed org.wildfly.checkstyle version.

- java/src/main/java/org/wildfly/openssl/OpenSSLClientSessionContext.java
- java/src/main/java/org/wildfly/openssl/OpenSSLSessionContext.java
- java/src/test/java/org/wildfly/openssl/ClientSessionTest.java
@stuartwdouglas, the commit here fixes a issue reported here https://github.com/wildfly/wildfly-openssl/issues/36 where the JVM consistently crashes due to a racy invalidation of the SSL client session. The commit includes a test case which reproduces this issue (in the absence of the fix in this PR) that causes the JVM to crash with:
```
malloc: *** error for object ...: pointer being freed was not allocated
```
The change in this commit involves removing the possibility of a race condition between the session cache management and invalidation, by letting the `OpenSSlSession#invalidate()` be the sole responsible authority for invalidating the session since it already has the necessary synchronization techniques to prevent the race conditions.
P.S: The referenced issue, seems to indicate …
> Fix JVM crash during client SSL session invalidation

- java/src/test/java/org/wildfly/openssl/BasicOpenSSLSocketDSATest.java
@stuartwdouglas, I was just testing against the 1.1.0 release of OpenSSL:
```
/usr/local/opt/openssl@1.1/bin/openssl version
OpenSSL 1.1.0f  25 May 2017
```
and the `BasicOpenSSLSocketDSATest#basicOpenSSLTest2` kept failing with:
```
javax.net.ssl.SSLHandshakeException: no cipher suites in common
at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1214)
at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1186)
at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)
at org.wildfly.openssl.EchoRunnable.lambda$run$0(EchoRunnable.java:92)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: no cipher …
```
> OpenSSL 1.1.0 - Enable TLS_DHE_DSS_WITH_AES_128_CBC_SHA for DSA test to pass

- java/src/main/java/org/wildfly/openssl/CipherSuiteConverter.java
- java/src/test/java/org/wildfly/openssl/BasicOpenSSLSocketDSATest.java
- libwfssl/include/wfssl.h
- libwfssl/src/ssl.c
Issue: https://issues.jboss.org/browse/WFSSL-10
> [WFSSL-10] NPE with wildfly-openssl using OpenSSL 1.1.1

- java/src/test/java/org/wildfly/openssl/BasicOpenSSLSocketTest.java
- java/src/test/java/org/wildfly/openssl/TestAllMethodsImplemented.java
- libwfssl/include/wfssl.h
- libwfssl/src/session.c
- libwfssl/src/ssl.c
- libwfssl/src/util.c
The main problem was that the method `tcn_Throw` just didn't include the real openssl message (so the %s was not filled with the real issue). I have used the standard `vsnprintf` with a 4096 buffer.
The other problem was that only the first openssl was retrieved instead the full stack. I decided to include the `ERR_print_errors` openssl method to dump all the stack into a buffer.
Because the messages can be longer now all the buffers have been increased from 256 to 2048.
Besides I have removed the include of the `opensslv.h` because the version checking should be done at runtime (never at compilation time). This was a mistake and complicates the compilation in windows.
If you prefer to allocate the buffers just let me know but I thought it was easier to respect original idea. The same if …
> WFSSL-15: Enabling one-way ssl using elytron with key length < 2048 returns non user friendly error message

- libwfssl/include/wfssl.h
- libwfssl/src/ssl.c
JIRA: https://issues.redhat.com/browse/WFSSL-23
It's just removing the static define for a dynamic version checking. This way the running openssl version is compared.
> WFSSL-23: Do not use static opensslv.h for version checking

- libwfssl/src/util.c
Fix for WFSSL-27. Just replacement of memcpy with memmove.
> [WFSSL-27] Use memmove instead of memcpy

- el6-i386/Makefile
- el6-i386/pom.xml
- el6-x86_64/Makefile
- el6-x86_64/pom.xml
- el7-x86_64/Makefile
- el7-x86_64/pom.xml
- el8-x86_64/Makefile
- el8-x86_64/pom.xml
- java/pom.xml
- pom.xml
This PR adds two new custom profiles for Linux `x86_64` and `i386` architectures that build the `${jboss.modules.os-name}-{x86_64|i386}` module. When building on different RHEL platforms, the following commands can now be used:
- RHEL 6: `mvn clean install -Djboss.modules.os-name=el6`
- RHEL 7: `mvn clean install -Djboss.modules.os-name=el7`
- RHEL 8: `mvn clean install -Djboss.modules.os-name=el8`
As an example, for the `x86_64` architecture, running `mvn clean install -Djboss.modules.os-name=el7` will result in a `wildfly-openssl-el7-x86_64` artifact in the `el7-x86_64` directory.
The same `jboss.modules.os-name` property would also need to be specified at runtime on RHEL platforms to make sure the right natives get loaded.
For the rest of the platforms, the build process is unchanged. …
> [WFSSL-31] Add the ability to make use of the 'jboss.modules.os-name' property when building on RHEL platforms

- java/src/main/java/org/wildfly/openssl/Identification.java
- linux-rhel6-i386/Makefile
- linux-rhel6-i386/pom.xml
- linux-rhel6-x86_64/Makefile
- linux-rhel6-x86_64/pom.xml
- linux-rhel7-x86_64/Makefile
- linux-rhel7-x86_64/pom.xml
- linux-rhel8-x86_64/Makefile
- linux-rhel8-x86_64/pom.xml
[MODULES-400](https://issues.redhat.com/browse/MODULES-400]) added an OS-version-specific category to the native search path that is used when loading the natives using JBoss Modules. The new OS-version-specific category is of the form `linux-rhel7-x86_64` as opposed to just `el7-x86_64`. In order for the RHEL natives to be loaded successfully, we need to update the directory names in the wildfly-openssl repo. We also need to update the native search path used by the `Identification` class to match this new format.
When building on different RHEL platforms, the following commands should now be used:
RHEL 6: `mvn clean install -Djboss.modules.os-name=linux-rhel6`
RHEL 7: `mvn clean install -Djboss.modules.os-name=linux-rhel7`
RHEL 8: `mvn clean install -Djboss.modules.os-name=linux-rhel8` …
> [WFSSL-39] [WFSSL-40] Update the OS-version-specific category that's added to the native search path to match the format used by JBoss Modules

- java/pom.xml
- java/src/main/java/org/wildfly/openssl/CipherSuiteConverter.java
- java/src/main/java/org/wildfly/openssl/Messages.java
- java/src/main/java/org/wildfly/openssl/OpenSSLClientSessionContext.java
- java/src/main/java/org/wildfly/openssl/OpenSSLContextSPI.java
- java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java
- java/src/main/java/org/wildfly/openssl/OpenSSLProvider.java
- java/src/main/java/org/wildfly/openssl/OpenSSLServerSessionContext.java
- java/src/main/java/org/wildfly/openssl/OpenSSLServerSocket.java
- java/src/main/java/org/wildfly/openssl/OpenSSLSessionContext.java
- java/src/main/java/org/wildfly/openssl/OpenSSLSocket.java
- java/src/main/java/org/wildfly/openssl/OpenSSlSession.java
- java/src/main/java/org/wildfly/openssl/SSL.java
- java/src/main/java/org/wildfly/openssl/SSLImpl.java
- java/src/main/resources/org/wildfly/openssl/OpenSSLMessages.properties
- java/src/test/java/org/wildfly/openssl/ALPNTest.java
- java/src/test/java/org/wildfly/openssl/BasicOpenSSLEngineTest.java
- java/src/test/java/org/wildfly/openssl/BasicOpenSSLSocketDSATest.java
- java/src/test/java/org/wildfly/openssl/BasicOpenSSLSocketTest.java
- java/src/test/java/org/wildfly/openssl/ClientCertTest.java
- java/src/test/java/org/wildfly/openssl/ClientSessionInteropTest.java
- java/src/test/java/org/wildfly/openssl/ClientSessionTest.java
- java/src/test/java/org/wildfly/openssl/ClientSessionTestBase.java
- java/src/test/java/org/wildfly/openssl/EchoRunnable.java
- java/src/test/java/org/wildfly/openssl/SslCiphersTest.java
- pom.xml
OpenSSL 1.1.1 added support for TLS 1.3. This PR adds support for TLS 1.3 to the WildFly OpenSSL provider.
https://issues.redhat.com/browse/WFSSL-16
https://issues.redhat.com/browse/WFSSL-36
> [WFSSL-16] Add support for TLS 1.3

- java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java
https://issues.redhat.com/browse/WFSSL-61
> [WFSSL-61] Avoid NPE if SSL_get_cipher returns "(NONE)"

- java/src/main/java/org/wildfly/openssl/OpenSSLContextSPI.java
- java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java
(Note: We should merge #96 and #97 before this one so we can trigger CI for this PR)
Remove broken `hasOp` checks for `SSL_OP_NO_COMPRESSION`, `SSL_OP_NO_TICKET`, and `SSL_OP_CIPHER_SERVER_PREFERENCE` since these ops have been present since before OpenSSL 1.0.1, which is the minimum required OpenSSL library version for WildFly OpenSSL.
This fix ensures that `SSL_OP_NO_TICKET` will always be set which fixes an issue a user ran into when using the WildFly OpenSSL provider with Jetty.
More details and discussions with Stuart can be found here:
https://issues.redhat.com/browse/WFSSL-65
> [WFSSL-65] Remove broken hasOp checks

- java/src/test/java/org/wildfly/openssl/BasicOpenSSLEngineLegacyProtocolsTest.java
Issue: https://issues.redhat.com/browse/WFSSL-72
Adding RSA ciphers for TLSv1 and TLSv1.1 and the special directive `@SECLEVEL=1` which sets security level to 1 (in ubunbtu 20.04 the default security level 2  avoids the use of those protocol versions, this is different in default openssl, fedora for example).
> [WFSSL-72] Investigate failures in BasicOpenSSLEngineLegacyProtocolsTest

- java/src/main/java/org/wildfly/openssl/OpenSSlSession.java
https://issues.redhat.com/browse/WFSSL-73
> [WFSSL-73]  Avoid an IllegalStateException when OpenSSLEngine#getSession is called if the OpenSSLEngine has been shut down

- java/pom.xml
- java/src/main/java/org/wildfly/openssl/ByteBufferUtils.java
- pom.xml
[WFSSL-76] Add parameter validation in ByteBufferUtils#expand method
https://issues.redhat.com/browse/WFSSL-76?filter=-1
- add validation for ByteBuffer and size inputs
> [WFSSL-76] Add parameter validation in ByteBufferUtils#expand method

- pom.xml
Issue: https://issues.redhat.com/browse/WFSSL-93
> [WFSSL-93] Set the natives version used to 2.2.0.Final

- java/src/test/java/org/wildfly/openssl/TestAllMethodsImplemented.java
- pom.xml
Issue: https://issues.redhat.com/browse/WFSSL-114
Upgrade for JUnit from 4.8.2 to 4.13.2. I also moved the version to a variable like we usually do (e.g. the elytron project).
> [WFSSL-114] Upgrade to JUnit 4.13.2
