wildfly-security/wildfly-openssl

libwfssl/src/ssl.c
Check OpenSSL library version as early as possible. Reason e.g.: older
versions of OpenSSL library might not have all searched symbols. Thus
loading/initialization ends with error message stating that some symbol
from library could not be read. But no hint about minimum version required
is printed.
=> Check OpenSSL library version as early as possible

linux-x86_64/Makefile
Jira: https://issues.jboss.org/browse/WFSSL-13
=> [WFSSL-13] Remove -Werror parameter from Makefile

pom.xml
Jira: https://issues.jboss.org/browse/WFSSL-12
=> [WFSSL-12] Upgrade parent pom version

libwfssl/src/ssl.c, linux-x86_64/Makefile
Add add the missing -Werror on linux-x86_64
=> Fix for https://issues.jboss.org/browse/WFSSL-14

java/src/main/java/org/wildfly/openssl/OpenSSlSession.java
https://issues.jboss.org/browse/WFSSL-19
=> WFSSL-19 Return Subject principal in SSLEngine.getPeerPrincipal()

java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java
https://issues.jboss.org/browse/WFSSL-20
=> WFSSL-20 Make OpenSSLEngine compatible with JDK 9+ ALPN APIs

libwfssl/src/util.c
Fix for WFSSL-25. The vsnprintf is just not used and a incomplete implementation is used (it's only for %s options, the ones that are used in the library).
=> [WFSSL-25] Don't use vsnprintf to format messages

libwfssl/src/session.c
https://issues.redhat.com/browse/WFSSL-51
=> [1.x][WFSSL-51]  sessions not removed correctly

java/src/main/java/org/wildfly/openssl/OpenSSLSessionContext.java, libwfssl/src/session.c
https://issues.redhat.com/browse/WFSSL-56
=> [1.0.x][WFSSL-56] Invalidate the removed session

java/src/test/java/org/wildfly/openssl/BasicOpenSSLEngineTest.java
https://issues.redhat.com/browse/WFSSL-60
=> [WFSSL-60] Add assertions to make sure the peer certificate chain is available from both the server and client sessions

java/src/main/java/org/wildfly/openssl/OpenSSLEngine.java
https://issues.redhat.com/browse/WFSSL-62
=> [WFSSL-62] Fix initial value for minProtocolIndex in OpenSSLEngine#setEnabledProtocols

.github/workflows/pr-ci.yaml, java/src/test/java/org/wildfly/openssl/ClientSessionTestBase.java
https://issues.redhat.com/browse/WFSSL-66
https://issues.redhat.com/browse/WFSSL-67
With these changes and with https://github.com/wildfly-security/wildfly-openssl/pull/96, CI passes successfully on Ubuntu, Windows, and macOS.
=> [WFSSL-66] / [WFSSL-67] Add a new GitHub workflow to trigger CI for pull requests and refactor some tests to avoid hangs

pom.xml
https://issues.redhat.com/browse/WFSSL-70
=> [WFSSL-70] update license name in the pom.xml to match the SPDX license name

java/src/main/java/org/wildfly/openssl/OpenSSlSession.java
https://issues.jboss..org/browse/WFSSL-71
=> WFSSL-71 Do not use javax.security.cert.X509Certificate

.github/workflows/pr-ci.yaml
runs so if we get a PR CI failure we can check if master still passes.
=> Add workflow_dispatch as a trigger for the action, this allows manual

.github/workflows/pr-ci.yaml, java/pom.xml
[WFSSL-84] Add JDK 17 build to Github Actions
https://issues.redhat.com/browse/WFSSL-81
https://issues.redhat.com/browse/WFSSL-84
=> [WFSSL-81] Ensure the project is buildable on JDK 17

combined/pom.xml, java/pom.xml
https://issues.redhat.com/browse/WFSSL-88
=> [WFSSL-88] Remove remaining references to windows-i386

java/src/main/java/org/wildfly/openssl/OpenSSLContextSPI.java
https://issues.jboss..org/browse/WFSSL-102
=> WFSSL-102 Allow creation of unbound server sockets

SECURITY.md
https://issues.redhat.com/browse/WFSSL-109
=> [WFSSL-109] Add SECURITY.md file

CODE_OF_CONDUCT.md
https://issues.redhat.com/browse/WFSSL-108
=> [WFSSL-108] Add CODE_OF_CONDUCT.md

CODEOWNERS
https://issues.redhat.com/browse/WFSSL-110
=> [WFSSL-110] Add a CODEOWNERS file to GitHub repository

.github/workflows/pr-ci.yaml
https://issues.redhat.com/browse/WFSSL-113
=> [WFSSL-113] Pull request CI should target main branch

README.md
Issue: https://issues.redhat.com/browse/WFSSL-107
=> [WFSSL-107] Add a note in the README about the OpenSSL versions that wildfly-openssl is compatible with
